### ISSUE TITLE
Can not receive password re-send mail nor forum password reseind mail.

### ISSUE THREAD

**Issue by qroft** [monaca/website#79]
I have just signed up via the Monaca CLI with my e-mail address and a chosen password.
I waited for 10 minutes in the CLI that got stuck at "please wait while we send you an activation mail...  etc."
I quit CMD and tried to login via the website.
I can login but as soon as i want to edit my account i come to a page saying "resend activation mail".
I click on it but this mail is never send out to me.

ON THE FORUMS:
Same here, i try to login and it does not work. It says that my address is already registered.
So i click on "forgot password" and there it asks me to enter my mail.
I enter my mail and hit resend.
But that activation mail never gets into my inbox.

I checked my SPAM and TRASH folders but nothing in there.

**Comment by masahirotanaka** [comment]
Sorry I just noticed it's on here. I guess the email problem is already fixed. Apologize we didn't check your issue until today!
